stages:
  - create_release_on_tag
  - test_build

variables:
  CI_IMAGE_UBUNTU: ubuntu:latest
  CI_IMAGE_DOCKER_GIT: docker:24.0.7-git
  CI_IMAGE_DIND: docker:24.0.7-dind
  CI_IMAGE_GITLAB_ACTIONS: ghcr.io/pczerkas/gitlab-actions:latest
  CI_IMAGE_ACT_PLATFORM: catthehacker/ubuntu:act-latest
  CI_IMAGE_BUILDKIT: moby/buildkit:v0.12.4
  MAIN_DOCKERFILE: build/package/docker/Dockerfile
  KIND_NODE_IMAGE: kindest/node:v1.29.0

  CI_DEBUG_SERVICES: "true"

.common_gcl_before_script: &common_gcl_before_script
  - |
    # needed by gcl
    if [ "$GITLAB_CI" = "false" ]; then sleep 2; fi

.common_docker_load_script: &common_docker_load_script
  - |
    if [ "$GITLAB_CI" = "false" ]; then
      echo "Step: Load images from host docker into dind"
      DOCKER_HOST=unix:///var/run/docker-host.sock \
        docker save \
          $CI_IMAGE_ACT_PLATFORM \
          $CI_IMAGE_BUILDKIT \
          $KIND_NODE_IMAGE \
      | \
      docker load
    fi

.common_act_default_args_script: &common_act_default_args_script
  - |
    # fix GitLab's non-symbolic-ref HEAD
    git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"

    act_default_args=(
      --platform ubuntu-latest=$CI_IMAGE_ACT_PLATFORM
      --env MAIN_DOCKERFILE=$MAIN_DOCKERFILE
      --env IMAGE_BUILDKIT=$CI_IMAGE_BUILDKIT
      --env KIND_NODE_IMAGE=$KIND_NODE_IMAGE
      --env GITLAB_CI=$GITLAB_CI
      --container-options "-v act-toolcache:/opt/hostedtoolcache"
      --no-skip-checkout
      --pull=false
      --use-gitignore=false
      --rebuild=false
      --privileged
      --verbose
      --rm
    )
    if [ -n "$DOCKER_REGISTRY_PROXY_HOST" ]; then
      act_default_args+=(
        --env DOCKER_REGISTRY_PROXY_HOST="$DOCKER_REGISTRY_PROXY_HOST"
        --env DOCKER_REGISTRY_PROXY_PORT="$DOCKER_REGISTRY_PROXY_PORT"
        --env NO_PROXY="$NO_PROXY"
        --env no_proxy="$NO_PROXY"
      )
    fi
    if [ -n "$SQUID_HOST" ]; then
      act_default_args+=(
        --env SQUID_HOST="$SQUID_HOST"
        --env SQUID_HTTP_PORT="$SQUID_HTTP_PORT"
        --env SQUID_HTTPS_PORT="$SQUID_HTTPS_PORT"
        --env NO_PROXY="$NO_PROXY"
        --env http_proxy="http://$SQUID_HOST:$SQUID_HTTP_PORT"
        --env https_proxy="http://$SQUID_HOST:$SQUID_HTTPS_PORT"
        --env no_proxy="$NO_PROXY"
      )
    fi

.common_job: &common_job
  image:
    name: $CI_IMAGE_GITLAB_ACTIONS
    # pull_policy: if-not-present
    pull_policy: always
  services:
    - name: $CI_IMAGE_DIND
      command: ["--tls=false"] # to ommit 15s delay
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - *common_gcl_before_script

.common_stage_create_release_on_tag_job: &common_stage_create_release_on_tag_job
  <<: *common_job
  stage: create_release_on_tag
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never

.common_stage_test_build_job: &common_stage_test_build_job
  <<: *common_job
  stage: test_build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - when: manual

build_and_release:
  <<: *common_stage_create_release_on_tag_job
  script:
    - *common_docker_load_script
    - *common_act_default_args_script
    - |
      act \
        "${act_default_args[@]}" \
        --workflows .github/workflows/release_tags.yml \
        --job build_and_release

verify_helm:
  <<: *common_stage_test_build_job
  script:
    - *common_act_default_args_script
    - |
      act \
        "${act_default_args[@]}" \
        --workflows .github/workflows/test_build.yml \
        --job verify_helm

verify_build:
  <<: *common_stage_test_build_job
  script:
    - *common_docker_load_script
    - *common_act_default_args_script
    - |
      act \
        "${act_default_args[@]}" \
        --workflows .github/workflows/test_build.yml \
        --job verify_build

e2e:
  <<: *common_stage_test_build_job
  script:
    - *common_docker_load_script
    - *common_act_default_args_script
    - |
      act \
        "${act_default_args[@]}" \
        --workflows .github/workflows/test_build.yml \
        --job e2e
