name: Release Tags

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_release:
    name: Build and release stable image
    runs-on: ubuntu-latest
    env:
      GORELEASER_VERSION: "1.23.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.RELEASE_USER_TOKEN }}

      - name: Set GoReleaser current tag
        env:
          REPOSITORY_NAME: ${{ github.repository }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
        # chart-releaser latest tag has non-semver format, need to convert it
        run: |
          echo "REPOSITORY_NAME: ${REPOSITORY_NAME}"
          echo "REPOSITORY_OWNER: ${REPOSITORY_OWNER}"
          REPOSITORY_SHORT_NAME=${REPOSITORY_NAME//${REPOSITORY_OWNER}\//}
          echo "REPOSITORY_SHORT_NAME: ${REPOSITORY_SHORT_NAME}"
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "LATEST_TAG: ${LATEST_TAG}"
          echo "GORELEASER_CURRENT_TAG=${LATEST_TAG//${REPOSITORY_SHORT_NAME}\-/v}" >> "$GITHUB_ENV"
          echo "GITHUB_ENV: BEGIN"
          cat ${GITHUB_ENV}
          echo "GITHUB_ENV: END"
      - name: Generate CACHEBUST variable
        run: echo CACHEBUST=$(date +%s) >> $GITHUB_ENV
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_USER_TOKEN }}
          CACHEBUST: ${{ env.CACHEBUST }}
        with:
          version: ${{ env.GORELEASER_VERSION }}
          args: release -f build/ci/.goreleaser.yml --clean --debug --verbose

      - name: Install Ripgrep
        run: |
          sudo apt-get -y update
          sudo apt-get -y install ripgrep

      - name: Test Docker image
        run: |
          # should panic when running outside of Kubernetes
          output=$(docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest 2>&1 || true)
          echo "$output" \
            | rg --passthru 'panic: unable to load in-cluster configuration'

      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          dockerfile: ./build/package/docker/Dockerfile
          severity: HIGH,CRITICAL
          # severity_threshold: HIGH
          annotations: true

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: chart
        env:
          CR_TOKEN: "${{ secrets.RELEASE_USER_TOKEN }}"
