name: Release Tags

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build and release stable image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      # - name: Docker login
      #   run: docker login -u "${{ secrets.QUAY_IO_USER }}" -p "${{ secrets.QUAY_IO_TOKEN }}" quay.io

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.RELEASE_USER_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #     tags: |
      #       type=semver,pattern={{version}}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: "0.181.1"
          args: release --rm-dist -f build/ci/.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_USER_TOKEN }}

      # - name: Run chart version bump
      #   uses: mittwald/bump-app-version-action@v1
      #   with:
      #     mode: 'publish'
      #     chartYaml: './chart/Chart.yaml'
      #   env:
      #     GITHUB_TOKEN: "${{ secrets.RELEASE_USER_TOKEN }}"
      #     HELM_REPO_PASSWORD: "${{ secrets.HELM_REPO_PASSWORD }}"

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: chart
        env:
          CR_TOKEN: "${{ secrets.RELEASE_USER_TOKEN }}"
