name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:

env:
  REGISTRY: ghcr.io
  MAIN_DOCKERFILE: build/package/docker/Dockerfile
  IMAGE_BUILDKIT: moby/buildkit:master@sha256:fd17acb9fd5b321401af2187b64c098cb28c2f7ce1749c8540f5f01ff5b32124

  # defines squid proxy to be used during build
  SQUID_HOST:
  SQUID_HTTP_PORT:
  SQUID_HTTPS_PORT:
  # defines docker registry proxy to be used during build
  DOCKER_REGISTRY_PROXY_HOST:
  DOCKER_REGISTRY_PROXY_PORT:
  # comma separated list of domains to bypass proxy
  NO_PROXY:

jobs:
  verify_helm:
    name: Verify Helm chart
    runs-on: ubuntu-latest
    strategy:
      matrix:
        helm: [ '3.1.2' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        run: |
          wget https://get.helm.sh/helm-v${{ matrix.helm }}-linux-amd64.tar.gz -O /tmp/helm.tar.gz
          tar xzf /tmp/helm.tar.gz -C /tmp --strip-components=1
          chmod +x /tmp/helm

      - name: Test template rendering
        run: /tmp/helm template ./chart/kube-apps-httpcache/.

      - name: Lint chart
        run: /tmp/helm lint ./chart/kube-apps-httpcache/

  verify_build:
    name: Verify Build
    runs-on: ubuntu-latest
    env:
      GORELEASER_VERSION: "1.23.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true

      - name: Set GoReleaser current tag
        env:
          REPOSITORY_NAME: ${{ github.event.repository.name }}
        # chart-releaser latest tag has non-semver format, need to convert it
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "GORELEASER_CURRENT_TAG=${LATEST_TAG//${REPOSITORY_NAME}\-/v}" >> "$GITHUB_ENV"
      - name: Generate CACHEBUST variable
        run: echo CACHEBUST=$(date +%s) >> $GITHUB_ENV
      - name: Run GoReleaser (on github)
        if: ${{ !env.ACT }}
        uses: goreleaser/goreleaser-action@v5
        env:
          SQUID_HOST: ${{ env.SQUID_HOST }}
          SQUID_HTTP_PORT: ${{ env.SQUID_HTTP_PORT }}
          SQUID_HTTPS_PORT: ${{ env.SQUID_HTTPS_PORT }}
          DOCKER_REGISTRY_PROXY_HOST: ${{ env.DOCKER_REGISTRY_PROXY_HOST }}
          DOCKER_REGISTRY_PROXY_PORT: ${{ env.DOCKER_REGISTRY_PROXY_PORT }}
          NO_PROXY: ${{ env.NO_PROXY }}
          CACHEBUST: ${{ env.CACHEBUST }}
        with:
          version: ${{ env.GORELEASER_VERSION }}
          args: release -f build/ci/.goreleaser.yml --snapshot --skip=publish --clean --debug --verbose
      - name: Run GoReleaser (on act)
        if: ${{ env.ACT }}
        uses: goreleaser/goreleaser-action@v5
        env:
          SQUID_HOST: ${{ env.SQUID_HOST }}
          SQUID_HTTP_PORT: ${{ env.SQUID_HTTP_PORT }}
          SQUID_HTTPS_PORT: ${{ env.SQUID_HTTPS_PORT }}
          DOCKER_REGISTRY_PROXY_HOST: ${{ env.DOCKER_REGISTRY_PROXY_HOST }}
          DOCKER_REGISTRY_PROXY_PORT: ${{ env.DOCKER_REGISTRY_PROXY_PORT }}
          NO_PROXY: ${{ env.NO_PROXY }}
          CACHEBUST: ${{ env.CACHEBUST }}
        with:
          version: ${{ env.GORELEASER_VERSION }}
          args: release -f build/ci/act/.goreleaser.yml --snapshot --skip=publish --clean --debug --verbose

  e2e:
    name: E2E
    runs-on: ubuntu-latest
    env:
      HELM_VERSION: 3.1.2
      REPOSITORY: local/kube-apps-httpcache
      TAG: "ci"
      KIND_CLUSTER_NAME: e2e
      KIND_NODE_IMAGE: kindest/node:v1.29.0@sha256:eaa1450915475849a73a9227b8f201df25e55e268e5d619312131292e324d570
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx (on github)
        if: ${{ !env.ACT }}
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Buildx (on act, using docker registry proxy and squid proxy)
        if: ${{ env.ACT && env.DOCKER_REGISTRY_PROXY_HOST != '' && env.SQUID_HOST != '' }}
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            # registry configures a new Docker register used for cache import or output.
            debug = true
            [registry."docker.io"]
              # mirror configuration to handle path in case a mirror registry requires a /project path rather than just a host:port
              #mirrors = ["yourmirror.local:5000", "core.harbor.domain/proxy.docker.io"]
              http = true
              insecure = true
              ca=["/etc/squid/CA.pem","/etc/docker-registry-proxy/CA.crt"]
              #[[registry."docker.io".keypair]]
              #  key="/etc/config/key.pem"
              #  cert="/etc/config/cert.pem"
          driver-opts: |
            "image=${{ env.IMAGE_BUILDKIT }}"
            "env.http_proxy=${{ env.DOCKER_REGISTRY_PROXY_HOST }}:${{ env.DOCKER_REGISTRY_PROXY_PORT }}"
            "env.https_proxy=${{ env.DOCKER_REGISTRY_PROXY_HOST }}:${{ env.DOCKER_REGISTRY_PROXY_PORT }}"
            "env.no_proxy='${{ env.NO_PROXY }}'"

      - name: Set up Docker Buildx (on act, using docker registry proxy)
        if: ${{ env.ACT && env.DOCKER_REGISTRY_PROXY_HOST != '' && env.SQUID_HOST == '' }}
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            # registry configures a new Docker register used for cache import or output.
            debug = true
            [registry."docker.io"]
              # mirror configuration to handle path in case a mirror registry requires a /project path rather than just a host:port
              #mirrors = ["yourmirror.local:5000", "core.harbor.domain/proxy.docker.io"]
              http = true
              insecure = true
              ca=["/etc/docker-registry-proxy/CA.crt"]
              #[[registry."docker.io".keypair]]
              #  key="/etc/config/key.pem"
              #  cert="/etc/config/cert.pem"
          driver-opts: |
            "image=${{ env.IMAGE_BUILDKIT }}"
            "env.http_proxy=${{ env.DOCKER_REGISTRY_PROXY_HOST }}:${{ env.DOCKER_REGISTRY_PROXY_PORT }}"
            "env.https_proxy=${{ env.DOCKER_REGISTRY_PROXY_HOST }}:${{ env.DOCKER_REGISTRY_PROXY_PORT }}"
            "env.no_proxy='${{ env.NO_PROXY }}'"

      - name: Set up Docker Buildx (on act, not using any proxy)
        if: ${{ env.ACT && env.DOCKER_REGISTRY_PROXY_HOST == '' && env.SQUID_HOST == '' }}
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            "image=${{ env.IMAGE_BUILDKIT }}"

      - name: Build image (using squid proxy)
        if: ${{ env.SQUID_HOST != '' }}
        run: |
          DOCKER_BUILDKIT=1 \
            http_proxy=http://${{ env.SQUID_HOST }}:${{ env.SQUID_HTTP_PORT }} \
            https_proxy=http://${{ env.SQUID_HOST }}:${{ env.SQUID_HTTPS_PORT }} \
            no_proxy=${{ env.NO_PROXY }} \
            docker buildx build \
              --progress plain \
              -f $MAIN_DOCKERFILE \
              --build-arg SQUID_HOST=$SQUID_HOST \
              --build-arg SQUID_HTTP_PORT=$SQUID_HTTP_PORT \
              --build-arg SQUID_HTTPS_PORT=$SQUID_HTTPS_PORT \
              --build-arg NO_PROXY=$NO_PROXY \
              --tag $REPOSITORY:$TAG \
              --provenance false \
              --load \
              .

      - name: Build image (not using squid proxy)
        if: ${{ env.SQUID_HOST == '' }}
        run: |
          DOCKER_BUILDKIT=1 \
            docker buildx build \
              --progress plain \
              -f $MAIN_DOCKERFILE \
              --tag $REPOSITORY:$TAG \
              --provenance false \
              --load \
              .

      - name: Set up Helm
        run: |
          wget https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz -O /tmp/helm.tar.gz
          tar xzf /tmp/helm.tar.gz -C /tmp --strip-components=1
          chmod +x /tmp/helm

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: ${{ env.KIND_CLUSTER_NAME }}
          version: v0.20.0
          config: build/ci/kind-config.yaml
          node_image: ${{ env.KIND_NODE_IMAGE }}
          verbosity: 99

      - name: Install test backend
        run: |
          kubectl get nodes
          kubectl get events -A --sort-by='.metadata.creationTimestamp'

          kubectl apply \
            -f test/test-backend.yaml

          sleep 10

          kubectl wait \
            pods --selector app=test-backend \
            --for condition=Ready \
            --timeout=5m30s \
          || \
            {
              kubectl get events -A --sort-by='.metadata.creationTimestamp' \
              && kubectl get pods -A -o wide \
              && exit 1; \
            }

          kubectl get events -A --sort-by='.metadata.creationTimestamp'

      - name: Install Helm chart
        run: |
          docker images
          kind load docker-image $REPOSITORY:$TAG --name $KIND_CLUSTER_NAME

          /tmp/helm install \
            -f test/chart-values.yaml \
            -f build/ci/chart-values-override.yaml \
            kube-apps-httpcache \
            ./chart/kube-apps-httpcache \
            --timeout 7m0s \
            --wait \
            --debug

          kubectl get pods -A
          kubectl get events -A --sort-by='.metadata.creationTimestamp'

      - name: Install Ripgrep
        run: |
          sudo apt-get -y update
          sudo apt-get -y install ripgrep

      - name: Run Tests
        run: |
          build/ci/tests/e2e.sh
